services:
  mysmpp:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysmpp:local
    container_name: mysmpp
    restart: unless-stopped
    ports:
      - "19087:19087"
      - "29175:29175"
    volumes:
      - mysmpp-data:/app/data

volumes:
  mysmpp-data:
