package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

var supplementalCodes = []string{
	"246", "247", "290", "672", "690", "800", "808", "870", "878", "881", "882", "883", "888", "979",
}

type cell struct {
	Ref  string `xml:"r,attr"`
	Type string `xml:"t,attr"`
	Val  string `xml:"v"`
	Text string `xml:"is>t"`
}

type row struct {
	Cells []cell `xml:"c"`
}

type worksheet struct {
	Rows []row `xml:"sheetData>row"`
}

type sharedString struct {
	Text  string   `xml:"t"`
	Parts []string `xml:"r>t"`
}

type sharedStrings struct {
	Items []sharedString `xml:"si"`
}

func main() {
	publicPath := flag.String("public", "", "public country XLSX")
	lengthPath := flag.String("lengths", "", "country length XLSX")
	outPath := flag.String("out", "", "generated Go file")
	flag.Parse()
	if *publicPath == "" || *lengthPath == "" || *outPath == "" {
		fail("public, lengths, and out are required")
	}

	publicRows, publicHash, err := readFirstSheet(*publicPath)
	if err != nil {
		fail("read public country: %v", err)
	}
	lengthRows, lengthHash, err := readFirstSheet(*lengthPath)
	if err != nil {
		fail("read country lengths: %v", err)
	}
	codes, err := countryCodes(publicRows)
	if err != nil {
		fail("parse public country: %v", err)
	}
	lengths, err := maxLengths(lengthRows)
	if err != nil {
		fail("parse country lengths: %v", err)
	}
	for _, code := range supplementalCodes {
		codes[code] = struct{}{}
	}
	for code := range lengths {
		if _, ok := codes[code]; !ok {
			fail("length rule country code %s is not recognized", code)
		}
	}

	source := generate(codes, lengths, publicHash, lengthHash)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fail("format generated source: %v", err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		fail("write generated source: %v", err)
	}
}

func countryCodes(rows [][]string) (map[string]struct{}, error) {
	index, err := headerIndex(rows, "region_code")
	if err != nil {
		return nil, err
	}
	codes := make(map[string]struct{})
	for _, values := range rows[1:] {
		if index >= len(values) {
			continue
		}
		code := strings.TrimSpace(values[index])
		if code == "" || len(code) > 3 {
			continue
		}
		if !digits(code) {
			return nil, fmt.Errorf("invalid region_code %q", code)
		}
		codes[code] = struct{}{}
	}
	return codes, nil
}

func maxLengths(rows [][]string) (map[string]int, error) {
	codeIndex, err := headerIndex(rows, "country code")
	if err != nil {
		return nil, err
	}
	lengthIndex, err := headerIndex(rows, "号码长度（最长）")
	if err != nil {
		return nil, err
	}
	lengths := make(map[string]int)
	for _, values := range rows[1:] {
		if codeIndex >= len(values) || lengthIndex >= len(values) {
			continue
		}
		code := strings.TrimSpace(values[codeIndex])
		if code == "" {
			continue
		}
		if !digits(code) {
			return nil, fmt.Errorf("invalid country code %q", code)
		}
		maxLen, err := strconv.Atoi(strings.TrimSuffix(strings.TrimSpace(values[lengthIndex]), ".0"))
		if err != nil || maxLen <= 0 {
			return nil, fmt.Errorf("invalid max length %q for %s", values[lengthIndex], code)
		}
		if maxLen > 15 {
			maxLen = 15
		}
		if existing, ok := lengths[code]; ok && existing != maxLen {
			return nil, fmt.Errorf("conflicting max lengths for %s: %d and %d", code, existing, maxLen)
		}
		lengths[code] = maxLen
	}
	return lengths, nil
}

func generate(codes map[string]struct{}, lengths map[string]int, publicHash, lengthHash string) string {
	codeList := make([]string, 0, len(codes))
	for code := range codes {
		codeList = append(codeList, code)
	}
	sort.Slice(codeList, func(i, j int) bool {
		if len(codeList[i]) != len(codeList[j]) {
			return len(codeList[i]) < len(codeList[j])
		}
		return codeList[i] < codeList[j]
	})
	lengthCodes := make([]string, 0, len(lengths))
	for code := range lengths {
		lengthCodes = append(lengthCodes, code)
	}
	sort.Slice(lengthCodes, func(i, j int) bool {
		if len(lengthCodes[i]) != len(lengthCodes[j]) {
			return len(lengthCodes[i]) < len(lengthCodes[j])
		}
		return lengthCodes[i] < lengthCodes[j]
	})

	var out strings.Builder
	out.WriteString("// Code generated by tools/countryrules; DO NOT EDIT.\n\npackage dispatch\n\n")
	fmt.Fprintf(&out, "const (\n\tpublicCountrySourceSHA256 = %q\n\tcountryLengthSourceSHA256 = %q\n)\n\n", publicHash, lengthHash)
	out.WriteString("var e164CountryCodes = map[string]struct{}{\n")
	for _, code := range codeList {
		fmt.Fprintf(&out, "\t%q: {},\n", code)
	}
	out.WriteString("}\n\nvar countryMaxTotalLength = map[string]int{\n")
	for _, code := range lengthCodes {
		fmt.Fprintf(&out, "\t%q: %d,\n", code, lengths[code])
	}
	out.WriteString("}\n")
	return out.String()
}

func readFirstSheet(path string) ([][]string, string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, "", err
	}
	digest := sha256.Sum256(data)
	reader, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return nil, "", err
	}
	shared := []string{}
	if file := zipFile(reader, "xl/sharedStrings.xml"); file != nil {
		payload, err := readZipFile(file)
		if err != nil {
			return nil, "", err
		}
		var table sharedStrings
		if err := xml.Unmarshal(payload, &table); err != nil {
			return nil, "", err
		}
		for _, item := range table.Items {
			shared = append(shared, item.Text+strings.Join(item.Parts, ""))
		}
	}
	file := zipFile(reader, "xl/worksheets/sheet1.xml")
	if file == nil {
		return nil, "", fmt.Errorf("sheet1.xml not found")
	}
	payload, err := readZipFile(file)
	if err != nil {
		return nil, "", err
	}
	var sheet worksheet
	if err := xml.Unmarshal(payload, &sheet); err != nil {
		return nil, "", err
	}
	rows := make([][]string, 0, len(sheet.Rows))
	for _, item := range sheet.Rows {
		values := []string{}
		for _, entry := range item.Cells {
			column := cellColumn(entry.Ref)
			for len(values) <= column {
				values = append(values, "")
			}
			value := entry.Val
			switch entry.Type {
			case "s":
				index, err := strconv.Atoi(value)
				if err != nil || index < 0 || index >= len(shared) {
					return nil, "", fmt.Errorf("invalid shared string index %q", value)
				}
				value = shared[index]
			case "inlineStr":
				value = entry.Text
			}
			values[column] = value
		}
		rows = append(rows, values)
	}
	return rows, hex.EncodeToString(digest[:]), nil
}

func headerIndex(rows [][]string, name string) (int, error) {
	if len(rows) == 0 {
		return 0, fmt.Errorf("empty worksheet")
	}
	for index, value := range rows[0] {
		if strings.TrimSpace(value) == name {
			return index, nil
		}
	}
	return 0, fmt.Errorf("header %q not found", name)
}

func cellColumn(ref string) int {
	column := 0
	for _, char := range ref {
		if char < 'A' || char > 'Z' {
			break
		}
		column = column*26 + int(char-'A'+1)
	}
	return column - 1
}

func digits(value string) bool {
	for _, char := range value {
		if char < '0' || char > '9' {
			return false
		}
	}
	return value != ""
}

func zipFile(reader *zip.Reader, name string) *zip.File {
	for _, file := range reader.File {
		if file.Name == name {
			return file
		}
	}
	return nil
}

func readZipFile(file *zip.File) ([]byte, error) {
	reader, err := file.Open()
	if err != nil {
		return nil, err
	}
	defer reader.Close()
	return io.ReadAll(reader)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
